apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: Jenkins-demo
    app.kubernetes.io/instance: Jenkins-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: jenkins-devsecops
  namespace: jenkins-devsecops
spec:
  selector:
    app: jenkins-devsecops
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 4000
